CREATE TABLE prediagnostico (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(300) NOT NULL,
    data_diagnostico DATE NOT NULL,
    resultado VARCHAR2(50) NOT NULL,
    tratamento_recomendado VARCHAR2(50) NOT NULL,
    setor_recomendado VARCHAR2(50) NOT NULL,
    observacoes VARCHAR2(300),
    paciente_id NUMBER,
    medico_id NUMBER
);
