CREATE TABLE consulta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_consulta DATE NOT NULL,
    horario_consulta TIMESTAMP NOT NULL,
    paciente_id NUMBER,
    medico_id NUMBER
);
